### ISSUE TITLE
Create Post Package structure (Including Post and UniquePostList)

### ISSUE THREAD

**Issue by KaydenKhor** [AY2122S2-TIC4002-F18-6/tp2#19]
The design of the Post class structure.

**Comment by KaydenKhor** [comment]
![image](https://user-images.githubusercontent.com/54035957/156212795-cdda846b-1365-4a29-9936-802153132e29.png)

**Comment by Ruiting1** [comment]
Currently `Post` have 5 fields: 
- Title
- Content
- PostDate
- Category
- Notes

![image](https://user-images.githubusercontent.com/44887123/156562980-a49ddfa4-c61e-4722-83d8-5b2946b9f02a.png)

For now, all the fields are **String** format, for **PostDate** need change to **DateTime** format, will create a separate issue for it
