### ISSUE TITLE
/delete content [index] [index] … 

### ISSUE THREAD

**Issue by KaydenKhor** [AY2122S2-TIC4002-F18-6/tp2#4]
/delete content 1 2 3 
As a social media manager, I want to be able to delete post from my planner so that if I delete the respective social media post, it would be reflected in the planner

**Comment by KaydenKhor** [comment]
Currently, the delete function can only delete 1 person, edit the function so that it can delete more than 1 in a single line command. No limits. separation by space

**Comment by Ruiting1** [comment]
I will just take over this one
